### ISSUE TITLE
Implement Result using structured or string errors

### ISSUE THREAD

**Issue by sffc** [rust-diplomat/diplomat#102]
Currently, we use a boolean to indicate success or failure:

```rust
    pub struct ICU4XFixedDecimalFormatResult {
        /// The [`ICU4XFixedDecimalFormat`], exists if creation was successful.
        pub fdf: Option<Box<ICU4XFixedDecimalFormat>>,
        /// Whether creating the [`ICU4XFixedDecimalFormat`] was successful.
        pub success: bool,
    }
```

We should make the error more expressive.  Here are some ways to do this:

1. Return a string with the error message (most likely an allocated string requiring destruction)
    - Pro: Easy to implement via `fmt::Display` in Rust
    - Pro: Implementations can return details to help the developer
    - Pro: FFI clients have as much debugging info as Rust clients
    - Con: Requires freeing the error string on the target
    - Con: Uncertain implications on code size since `fmt::Display` can be heavy at times
    - Con: Code recovering from errors needs to parse the string
    - Con: Allocating the string could fail
2. Return an error code as an integer, which can be looked up in a table to determine what kind of error it is
    - Pro: Consistent with ICU4C
    - Pro: Lightweight, highly portable option
    - Con: Non-expressive error with limited utility
    - Con: Requires maintaining a public dictionary somewhere of error codes to what they mean
    - Con: Requires changes to Rust code to generate the integer value
3. Return an error code as a TinyStr16 (ascii encoded as u128); for example, "INT_OVERFLOW"
    - Pro: Lightweight
    - Pro: New error types can be added without updating a central dictionary
    - Con: Requires changes to Rust code to generate the TinyStr16

Let's decide on a strategy first, and then prioritize implementing it in time for ICU4X 1.0.

**Comment by Manishearth** [comment]
We have Result support
