### ISSUE TITLE
had I known about diplomat I might not have written ffi-gen

### ISSUE THREAD

**Issue by dvc94ch** [rust-diplomat/diplomat#118]
looks like diplomat has similar ambitions to ffi-gen. we currently support wasm/js and dart/flutter and can generate bindings for high level concepts like objects/iterators/futures/streams. guessing it's too late for any meaningful collaboration now.

- [0] https://github.com/cloudpeers/ffi-gen

**Comment by Manishearth** [comment]
Heh that would be pretty neat. We do want Dart/flutter support and probably could collab, though I think adding async would be a lot of work at this point

**Comment by dvc94ch** [comment]
well, so our system actually works and we're going to continue using it at least for the time being. supporting c/c++ wouldn't be very easy in ffi-gen, as we mostly deal with high level concepts, and the generated api which is basically what a c program would use, is not "pretty". I was really attached to the idea of a rust header file that completely describes the api and contains all the information for ergonomic bindings. However this has two downsides. 1. you actually need to make changes in two places. at least it's a compile failure if there's a missmatch, but with ffi-gen it becomes a large part of the work of adding/changing apis. 2. you can't nest impl Trait's in rust. which means we need access to the actual concrete type to concretize. imagine `Stream<Iterator<string>>`. the only reason this currently works is because we made the `Iterator` be synonimous with a `Vec`, which is unfortunate because we could really support any type that implements `IntoIterator`.
