### ISSUE TITLE
Namespace C functions (symbols) with crate name

### ISSUE THREAD

**Issue by CBenoit** [rust-diplomat/diplomat#128]
Currently Diplomat desugars
```rust
#[diplomat::bridge]
pub mod ffi {
    #[diplomat::opaque]
    pub struct MyStruct;

    impl MyStruct {
        fn my_func(&self) {
            // -- snip -- //
        }
    }
}
```
into
```rust
#[no_mangle]
extern "C" fn MyStruct_my_func() {
    // -- snip -- //
}
```
It's not a issue if name of the struct is enough to "namespace", but it might be good to prevent clashes by prepending crate's name such that we export the symbol `my_crate_MyStruct_my_func` instead:
```rust
#[no_mangle]
extern "C" fn my_crate_MyStruct_my_func() {
    // -- snip -- //
}
```
The C API might suffer a bit from that, but my understanding is that [the C API is not expected to be ergonomic](https://github.com/rust-diplomat/diplomat/blob/6a9420b915635c15697dcbeeb0f5dcf6d9878d57/docs/design_doc.md#builtin-types).

**Comment by Manishearth** [comment]
Actually, I've wanted _bridge_ modules to be able to declare namespaces as well. Perhaps we allow each bridge module to declare `#[diplomat::bridge] #[diplomat::namespace(common = icu, plurals)] mod ffi {}`? This way the backends can also apply such namespaces as desired. The "common" namespace has to match between bridge calls and is where everything is placed.

**Comment by CBenoit** [comment]
Oh, so for `diplomat::namespace(common = icu, plurals)`, exposed symbol would be `icu_MyStruct_my_func`, and generated C++ wrapper would be roughly
```cpp
namespace icu {
  namespace plurals {
    class MyStruct {
      void my_func() {
        capi::icu_MyStruct_my_func();
      }
    }
  }
}
```
Am I correct?

**Comment by Manishearth** [comment]
yeah though _perhaps_ the C stuff shoudl be icu_plurals_foo? idk @sffc do you have thoughts?

The reason I have "common" as separate is so that diplomat_runtime.hpp has a namespace it can go into as well.

The nice thing is that we'll be able to remove the forced namespacing from our Diplomat APIs then.

**Comment by CBenoit** [comment]
> The reason I have "common" as separate is so that diplomat_runtime.hpp has a namespace it can go into as well. Otherwise this should just be a list.

Oh, I understand. `icu_plurals_foo` sounds good then.

It’s worth noting that Java and C# have conventions a bit different from Rust and C++ when it comes to namespace naming conventions, typically wrapping everything into a company-wide namespace (`com.company.product.something`, `Company.Product.Something`, …).
However it’s easy to make this configurable in the backend-specific configuration, so I think with your approach we can cover pretty much all the interesting use cases.

**Comment by Manishearth** [comment]
Yeah. Perhaps we need to do this via `diplomat_attr()` instead? Previously discussed in https://github.com/rust-diplomat/diplomat/issues/127

I think we need `diplomat_attr()` for talking to backends _in general_.

**Comment by Manishearth** [comment]
#416 fixes this
