### ISSUE TITLE
Support for `Option` in function's parameters and return values

### ISSUE THREAD

**Issue by CBenoit** [rust-diplomat/diplomat#132]
Is supporting `Option` parameters out of scope for Diplomat?

> […]
> Basically, input types should not have:
>
> - Options not wrapping refs
> […]

_@Manishearth in https://github.com/rust-diplomat/diplomat/issues/130#issuecomment-1028165109_

I was thinking we could define a FFI-safe `DiplomatOption` (similar to how we have a `DiplomatResult`) precisely to support this kind of use case (receiving `Option` not wrapping refs) such that:
```rust
fn take_opt_integer(a: DiplomatOption<u32>) { … }
```
or
```rust
fn take_opt_integer(a: Option<u32>) { … }
```
desugars into
```rust
extern "C" fn MyType_take_opt_integer(a: DiplomatOption<u32>) { … }
```

Definitely not an immediate priority, but would you be open to that?

**Comment by Manishearth** [comment]
Yeah I'm down to add DiplomatOption, it would be complicated but doable.

**Comment by CBenoit** [comment]
Good! This can be a long-term improvement

**Comment by sffc** [comment]
This issue title says "parameters and return values" but we should also support optional fields of structs
