### ISSUE TITLE
update to latest version to crates.io

### ISSUE THREAD

**Issue by leejw51crypto** [rust-diplomat/diplomat#135]
cargo install diplomat-tool, and using it generates error in example.
but using diplomat-tool directly from github works

```
use diplomat_runtime::DiplomatWriteable;..
DiplomatWriteable
```
for above code, using diplomat-tool directly from github worked.
but using diplomat-tool from cargo install not worked.

**Comment by Manishearth** [comment]
Overall diplomat is still changing so we're not committed to maintaining it on crates.io yet.

However if you make a PR bumping the versions to 0.3.0 I'd be happy to merge and publish.
