### ISSUE TITLE
Support versioning for the C API

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#137]
It's often desired for C dylibs to be ABI-stable. We should add support for `#[diplomat::c_version_suffix = "_v1"]` so that tagged functions get a suffix in the C code, and the headers automatically use it.

We may need to do something for destructors and other functions that get autogenerated.

**Comment by sffc** [comment]
How about putting the version first, adjacent to the crate name, like

`icu4x_v1_fixed_decimal_format_create()`

**Comment by Manishearth** [comment]
ah, we should add support for crate names in the API too :smile:

**Comment by Manishearth** [comment]
#416 gives us this ability now.
