### ISSUE TITLE
Multi-level borrows don't work

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#142]
```rust

struct Foo<'a>(&'a str);
struct Bar<'b, 'a>(&'b Foo<'a>);

#[diplomat::opaque]
struct ICU4XFoo<'a>(Foo<'a>);


#[diplomat::opaque]
struct ICU4XBar<'b, 'a>(Bar<'b, 'a>)

impl<'a> ICU4XFoo<'a> {
   pub fn new(x: &str) -> Box<ICU4XFoo<'a>> {
       .....
   }

   pub fn get_bar<'b>(&'b self) -> Box<ICU4XBar<'b, 'a>> {
       ....
   }
}
```

The generated Rust code will fail to compile because `get_bar` generates a lifetimeless `ICU4XFoo_get_bar()` function. When there's a single lifetime in play this is fine, but this rapidly breaks down as there are multiple.

This is probably something to fix as a part of https://github.com/rust-diplomat/diplomat/issues/12.

**Comment by Manishearth** [comment]
@qnnokabayashi might be working on some of this

**Comment by Manishearth** [comment]
First step: https://github.com/rust-diplomat/diplomat/pull/147

**Comment by QnnOkabayashi** [comment]
Can you give a brief example of what `ICU4XFoo::get_bar` might get expanded to? Where would the lifetimes end up on the method invocation? From what I can tell from the src, it seems like the `extern "C"` wrapper would take ptrs instead of references?

**Comment by QnnOkabayashi** [comment]
Currently working on this and want to double check, we expect `ICU4XFoo::get_bar` to generate the following, right?
```rust
#[no_mangle]
extern "C" fn ICU4XFoo_get_bar<'a, 'b>(this: &'b ICU4XFoo<'a>) -> Box<ICU4XBar<'b, 'a>> {
    this.get_bar()
}
```

**Comment by Manishearth** [comment]
Yep!
