### ISSUE TITLE
Support lifetime elision in return types

### ISSUE THREAD

**Issue by QnnOkabayashi** [rust-diplomat/diplomat#160]
Currently, `ast::Method::params_held_by_output` (added in #159) relies on explicit lifetimes in the return type to determine which `Param`s the output type is lifetime-bound to. We should implement lifetime elision inference so we can lift this restriction, allowing for methods like:
```rust
fn foo(x: &Opaque) -> Foo<&Opaque> { ... }
```

I think we can assume in our elision inference implementation that we will never encounter an ambiguous case, since that would be caught by rustc.

**Comment by QnnOkabayashi** [comment]
I think that the new HIR is the perfect opportunity to implement this, with some minor redesign.

I think the way to approach is is to some `LifetimeEnv`-like type in `ast` that just extracts all explicit lifetime bounds from generic arguments, and nothing more. Then, we use this in the lowering to HIR phase to go through and figure out what all the elided lifetimes are, adding any implicit bounds that they may have like what https://github.com/rust-diplomat/diplomat/issues/198 does. Finally, we move the "all longer/shorter lifetimes" DFS algorithm and other fancy things to `hir::LifetimeEnv`.

**Comment by Manishearth** [comment]
Yep! Though we should move everyone over to HIR first I guess 😄

**Comment by Manishearth** [comment]
Closing in favor of #411, oops
