### ISSUE TITLE
Remove intermediate `Uint8Array`s during slice conversion

### ISSUE THREAD

**Issue by QnnOkabayashi** [rust-diplomat/diplomat#174]
#172 introduces the `DiplomatBuf` class in `diplomat_runtime.js`, which basically handles conversion from JS strings and primitive slices to arrays in wasm memory that Rust can read, which allows us to reduce boilerplate in the codegen.

Currently, we use `TextEncoder.encode` to encode strings into a `Uint8Array`, and then copy that into a view of wasm memory. We should be using [`TextEncoder.encodeInto`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto) to avoid this intermediate array.

For slices, we use the `Uint8Array` constructor to convert an iterable of JS numeric objects into an array, and then copy that into wasm memory. We should look into if there are any alternatives like how strings have`encodeInto` that would allow us to skip this intermediate array, and then use those if possible.

**Comment by QnnOkabayashi** [comment]
Question: for `TextEncoder.encodeInto`, we would first need to get a view into the `wasm.memory.buffer`, which requires us to know the length. Can we assume the length of the view is going to be the number of characters in the string? If not, how do we determine how much space it's going to take?

**Comment by robertbastian** [comment]
> Can we assume the length of the view is going to be the number of characters in the string?

JS's `String.length` is the number of UTF-16 code points (two bytes each), but `TextEncoder.encodeInto` encodes into UTF-8. The UTF-8 length depends on the actual characters in the string:
* U+0000 - U+007F (ASCII): one UTF-8 byte (and one UTF-16 code point)
* U+0080 - U+07FF: two UTF-8 bytes (and one UTF-16 code point)
* U+0800 - U+FFFF: three UTF-8 bytes (and one UTF-16 code point)
* U+10000 - U+10FFF: four UTF-8 bytes (and _two_ UTF-16 code points)

So the UTF-8 buffer length will be something between 1x and 3x `String.length`, and determining the exact number requires inspecting the whole string.

`TextEncoder.encodeInto` has a section on this: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto#buffer_sizing

**Comment by Manishearth** [comment]
Yeah, and figuring out that length requires doing an operation that costs similarly to the decoding itself (though it doesn't require allocation).

If we can pass down the string as UTF16 to Rust we shpould do this, otherwise probably not.

We might be able to do this for slices though.

**Comment by Manishearth** [comment]
Right, I meant that the rust-side conversion will likely be faster, and we'd avoid an additional copy, since TextEncoder.encode can only (I _think_?) write to JS memory, not wasm memory, so we always do an extra copy.

**Comment by QnnOkabayashi** [comment]
> 2. Compute the required string length in JS, then allocate the exact number of bytes, then perform a second pass to copy them into the WASM buffer

For this option, would we go with `new Blob([string]).size`?

**Comment by Manishearth** [comment]
No, we'd have to compute the length in UTF8, that would be UTF16

**Comment by robertbastian** [comment]
For slice this isn't possible, as the input type could be any array, and we have no idea what its length in bytes will be.
