### ISSUE TITLE
Allow `&str` in non-opaque structs for C/C++

### ISSUE THREAD

**Issue by QnnOkabayashi** [rust-diplomat/diplomat#175]
#172 intends to add support for non-opaque structs to contain other non-opaque structs and `&str`s in JS. It doesn't yet provide support for C/C++ yet, but the PR is already too bloated. Thus, we should write the C/C++ support for borrowed strings and primitive slices in non-opaque structs.

**Comment by QnnOkabayashi** [comment]
I think there's also an issue where in methods that take a non-opaque struct by value (so all of them), it generates C code like
```c
MyStruct diplomat_wrapped_struct_this = this;
```
Where `this` is a `MyStruct*`, so it doesn't work.

**Comment by Manishearth** [comment]
I've got fixes for this in https://github.com/Manishearth/diplomat/tree/pr-172

**Comment by Manishearth** [comment]
https://github.com/rust-diplomat/diplomat/pull/177
