### ISSUE TITLE
`usize` is missing in TypeScript

### ISSUE THREAD

**Issue by sffc** [rust-diplomat/diplomat#218]
I got the following compile error when running `tsc` in the ICU4X lib directory

```
../icu4x/lib/ICU4XBidiInfo.d.ts:16:22 - error TS2304: Cannot find name 'usize'.

16   paragraph_count(): usize;
                        ~~~~~
```

I worked around it by adding `usize` to diplomat-runtime.d.ts. Is it missing? @QnnOkabayashi

**Comment by QnnOkabayashi** [comment]
Fixed in https://github.com/rust-diplomat/diplomat/pull/219
