### ISSUE TITLE
rust_link should have a hidden option

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#223]
Currently we use rust_link for two purposes:

 - Linking to the original type in the docs
 - Handling coverage checks

The problem is that sometimes an FFI API covers many facets of one Rust API, but it's noisy to have ten links in the docs.

Perhaps we should either have a `diplomat::covers_api` or `diplomat::rust_link_hidden` or something? Alternatively, have `diplomat::rust_link_extra` which renders as "Extra documentation links: [1](x), [2](x), [3](x), [4](x), [5](x)". Maybe even both.

cc @robertbastian  @sffc

**Comment by sffc** [comment]
`diplomat::rust_link_extra` SGTM.

**Comment by Manishearth** [comment]
This exists
