### ISSUE TITLE
Move coercion detection from `ast::LifetimeEnv` to `hir::LifetimeEnv`

### ISSUE THREAD

**Issue by QnnOkabayashi** [rust-diplomat/diplomat#229]
With the new HIR, a lot of the functionality that I originally added to `ast::LifetimeEnv` should be moved into `hir::LifetimeEnv`. This includes things like tracking which lifetimes can coerce into which other lifetimes and such. I think ultimately, `ast::LifetimeEnv` should simply track explicit lifetime bounds and lifetimes in scope.

It also would be a good idea to make them have different names, since the ast one will do basic tracking, while the hir one will do more sophisticated analysis.

**Comment by Manishearth** [comment]
This is probably post-migration, yes? Since otherwise we'd regress functionality?
