### ISSUE TITLE
Support exposing &[u16] as std::u16string_view and u16 as char16_t

### ISSUE THREAD

**Issue by hsivonen** [rust-diplomat/diplomat#240]
In text-oriented Rust code like ICU4X, `&[u16]` is used for UTF-16 and, therefore, has `std::u16string_view` semantics, and `u16` is used for UTF-16 code unit and, therefore, has `char16_t` semantics. Add configuration options to have these types generated for C++.

**Comment by Manishearth** [comment]
We definitely use u16 for non char16_t reasons in ICU4X, fwiw

**Comment by robertbastian** [comment]
#367 #368
