### ISSUE TITLE
Support const in span T

### ISSUE THREAD

**Issue by hsivonen** [rust-diplomat/diplomat#241]
`mozilla::Span` uses the old GSL design, where `const` goes inside `T`: That is, Rust `&[u32]` maps to `mozilla::Span<const uint32_t>`.

Diplomat does not appear to support this pattern in tool/src/cpp/configs/mfbt.toml even though the mapping for `&str` uses this pattern.

**Comment by Manishearth** [comment]
I believe Diplomat's cpp2 backend supports this.

However, configuration support may need to be added again.
