### ISSUE TITLE
Returning references in C++ [switching C++ over to external allocation]

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#242]
Currently all C++ opaques look like this:

```cpp
class Opaque {
  // ...

  std::unique_ptr<capi::Opaque, OpaqueDeleter>;
}
```

This means that the allocation is internal to the type: we can return `Opaque`s and accept `Opaque&`s , however we cannot return `Opaque&`s because there is no struct on the Rust side containing this unique_ptr.

Diplomat does have support for returning references, especially with `transparent_convert`, and it's rather nice to be able to design APIs around this. JS handles this with an `owned` flag on all opaques.

We could do something similar, but, ideally, our architecture is better about this.

I think we should move our C++ backend over to:

 - `Opaque` types are internally opaque (not sure how to do this but still have methods on them. Perhaps just a private constructor?)
 - constructors for opaque types return `unique_ptr<Opaque,OpaqueDeleter>` (for convenience, we can alias this to `Opaque::Owned`
 - references are returned as `Opaque&`

I'm not quite sure how to do the first step in C++: C++ does let you do opaque (pointer-only) types by forward declaring them without definition; however it does not let you do that if you add methods.

An alternate solution would be to add a separate OpaqueRef class that can be copy-constructed from Opaque, and use that everywhere.

**Comment by Manishearth** [comment]
For now perhaps returning Ref types may be the best? it's not ideal since it's 2x the files but it ought to work

**Comment by sffc** [comment]
My understanding of C++ style is that you should return a `unique_ptr<T>` if you are handing off ownership, or either a `const *T` or a `const &T` if you are not handing off ownership.

To achieve this, I think you can make C++ be a zero-sized type with private constructors and then reinterpret_cast from the C type to the C++ type. The unique_ptr sees the C++ type, so you would tack on a custom deleter function.

**Comment by Manishearth** [comment]
> To achieve this, I think you can make C++ be a zero-sized type with private constructors and then reinterpret_cast from the C type to the C++ type. The unique_ptr sees the C++ type, so you would tack on a custom deleter function.

Yeah that's the long term plan I'm hoping for. Short term `Ref` may be less churny.

**Comment by Manishearth** [comment]
From Dmitri:

> as long as you don't provide any way to get or create a RustType in C++ by value, and you ensure that assignment operators are deleted or private, you can define the type with methods and a mismatched size and it shouldn't have negative consequences

> the trick is to ensure that whatever implicitly-generated ctors, assigment operators, dtors etc. either don't hurt you or don't exist
> 
>so it is best to declare them all with `= delete;` to make the intent clear and not play the guessing game about c++ rules


So in a pure greenfield world we ought to be able to do:

```cpp

class RustType {
   public:
   // delete all implicits
   std::unique_ptr<RustType> ctor();
   void method();
   RustType& referencey_method();
}

// override the delete operator
```

**Comment by Manishearth** [comment]
Wrote a small C++ program that uses all of this with fake integer pointers we can pretend come from Rust

<details>

```cpp
#include <memory>
#include <iostream>

class RustType {
public:
    RustType() = delete;
    RustType(const RustType&) = delete;
    RustType(RustType&&) = delete;
    RustType& operator=(const RustType&) = delete;
    RustType&& operator=(const RustType) = delete;

    // The following methods would actaully forward to rust impls
    static void operator delete(void* self) {
        std::cout<<"Deleting " << (intptr_t)self << std::endl;
    }

    static std::unique_ptr<RustType> ctor() {
        uintptr_t i = 100;
        std::unique_ptr<RustType> foo((RustType*)i);
        std::cout<<"Allocating " << i << std::endl;
        return foo;
    }
    uintptr_t method() {
        return (uintptr_t)this;
    };
    RustType& referency_method() {
        uintptr_t i = 200;
        RustType* foo = (RustType*)i;
        return *foo;
    }
};



int main() {
    std::unique_ptr<RustType> ptr = RustType::ctor();
    std::cout<< "Method returned " << ptr->method() <<std::endl;
    RustType& reference = ptr->referency_method();
    std::cout<< "Method returned " << reference.method() <<std::endl;
    // won't compile, yay
    // RustType foo = reference;

    // dtors work fine
    return 0;
}
```

</details>

**Comment by Manishearth** [comment]
Unfortunately, this is an API-breaking change. In the meantime we could probably do the substandard FooBorrowed version for the rare APIs that need to do such borrowing.

**Comment by sffc** [comment]
When we get namespace support, we can put the new and improved APIs inside the namespace.

**Comment by Manishearth** [comment]
It's going to be ugly for Diplomat to do _both_ simultaneously. But we can still add this support as a flag (like namespaces), and at least _start_ generating new-and-improved ICU4X cpp headers.

**Comment by Manishearth** [comment]
Fixed by cpp2
