### ISSUE TITLE
Allow using Result instead of DiplomatResult

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#245]
DiplomatResult is necessary over FFI, however the diplomat_macro codegen could absolutely introduce a `.into()` before calling the Rust function, enabling more idiomatic Rust (and usage of `?`)

Currently diplomat_macro code is rather simple and doesn't do many conversions like this, but it could.

The Diplomat HIR would not maintain a distinction (and the AST could maintain the distinction as a boolean ignored by backends still using the AST).

**Comment by robertbastian** [comment]
Fixed by #309
