### ISSUE TITLE
Support optional types

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#246]
We support optional opaques, but we do not support optional primitives and structs. We should; exposing it as `std::optional` in C++ and

We will likely want to do the same thing as https://github.com/rust-diplomat/diplomat/issues/245 where it's automatic when found in parameters, though we will have to require people to use DiplomatOption in struct types.

We could also make it so that you can force opaques into optionals if you really want (currently opaque+optional = nullable opaque)

Status: 
 - [x] Core support: https://github.com/rust-diplomat/diplomat/pull/558
 - [x] C/CPP: https://github.com/rust-diplomat/diplomat/pull/628
 - [ ] Dart: https://github.com/rust-diplomat/diplomat/pull/632
 - [ ] JS: Tyler will be working on this
 - [ ] Kotlin: jcrist1 may work on this

I shall consider this issue fixed when Dart, C, and CPP have landed.

**Comment by robertbastian** [comment]
#132

**Comment by Manishearth** [comment]
I'm going to reopen this, #132 only added them in return types. I'd like these to be supported everywhere.

This reduces the need for #247

**Comment by Manishearth** [comment]
What I'm going to try and do is make it so that:

(assume `T` is not a pointer type)

 - `DiplomatOption<T> = DiplomatResult<T, ()>`
 - `Option<T>` _or_ `DiplomatOption<T>` in a return type returns a result type, akin to the current behavior of `-> Option<T>`
 - `Option<Ptr>` always is a nullable pointer, in any position (as it is now)
 - `DiplomatOption<Ptr>` is forbidden
 - `Option<T>` in param lists is autoconverted to `DiplomatOption<T>`
 - `Option<T>` in struct fields is an error.

This means that some mixing of the two will magically work but in cases where the distinction matters you have to use the right type. We can document that.
