### ISSUE TITLE
Move all backends to HIR

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#252]
This is the last part of https://github.com/rust-diplomat/diplomat/issues/204

Earlier this summer, @QnnOkabayashi implemented the higher-level intermediate representation for Diplomat, in https://github.com/rust-diplomat/diplomat/pull/220, along with lowering from the AST to HIR (https://github.com/rust-diplomat/diplomat/pull/221).

The last step of this process is to move all backends to HIR. This can be done one backend at a time, but is hard to split up within that: each backend will need to be migrated wholesale.

At the end of this, `diplomat_macro` and HIR lowering itself should be the only two remaining consumers of the AST.

**Comment by Manishearth** [comment]
cc @CBenoit you may be interested in doing this for the .NET backend at some point. I'm a bit hesitant of saying that you should do this _now_ since we haven't yet migrated any other backend to the HIR yet (and there may be bugs we need to fix), but it's worth thinking about at least. Help migrating the other backends would of course be appreciated though, I was considering doing the simpler C backend first.

Overall the HIR ought to simplify the backend since you will no longer need to do resolution everywhere, and everything will be prevalidated so you won't have to spend time dealing with invalid states. But it's a bunch of work to do the migration.

**Comment by CBenoit** [comment]
Thank you for the ping! I’ve been following the progress on HIR and was planning on doing that at some point soonish. 🙂
I was contemplating the idea of moving to tera templates before, but might as well do both at once since it’ll be refactoring in both cases. Not sure.

**Comment by Manishearth** [comment]
Sounds good! We haven't yet explored tera much in the rest of Diplomat so I'm not yet sure how useful it would be but I'm interested in seeing what you make of it!

**Comment by Manishearth** [comment]
Discussed in ICU4X call today

Start: 8:25

- @Manishearth Is it time to migrate? Potential factors:
    - Dotnet backend doesn't have an HIR version yet
    - If we move to a point where features can't be supported by AST, we could delete
    - New CPP backend doesn't have doc support, we could add it
    - If people want the AST backend, they can use an old version
    - Biggest reason to avoid migration is if we decide the HIR backend doesn't work for us. CPP HIR backend is most polished however, and it's been working so far
- ICU4X is on JS2 so we can do this now. We don't use .NET.
- @robertbastian: I don't see a scenario when we go back to AST.
- @sffc Agreed.
