### ISSUE TITLE
Support `cfg`-ing methods

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#307]
This would have to be tracked in the AST to generate `extern "C"` wrappers with the same condition. Bindings could be unconditionally generated (which would lead to a linker error if the library is not compiled with the required features), or `diplomat-tool` could be taught about cfg as well.

**Comment by Manishearth** [comment]
https://github.com/rust-diplomat/diplomat/issues/233

**Comment by Manishearth** [comment]
nvm this is subtly different.

**Comment by robertbastian** [comment]
Yes that's what I'm proposing. The tool would need to be able to evaluate `cfg`s (and some of ours have not just `feature` but also `target`), so for a first version I think it's fine if it just ignores them. We already have documentation along the line of "this method needs this feature", but making this a link-time error instead of a runtime panic would be a win already.

**Comment by Manishearth** [comment]
Alright.

Let's get that first step done (are you interested in doing it?)

I'm working on proper attribute support in the AST and HIR and in the long run we can parse the cfg and stash it there too

**Comment by robertbastian** [comment]
Can do. Extern generation uses AST, right? Then we wouldn't have to add this to the HIR yet.

**Comment by Manishearth** [comment]
Yes. For now just stash the attribute vector on the AST

I plan to make that nicer but I can wait for your changes first
