### ISSUE TITLE
Provide something other than `char` for FFI

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#318]
`char` isn't actually ABI-defined (and improper_ctypes complains about it). We should use some wrapper around uint32_t at the ABI level

**Comment by robertbastian** [comment]
I think with `char` we actually get UB when a caller passes a non-char 4-byte value, maybe even sooner.

**Comment by robertbastian** [comment]
Discussed in the meeting:

* As there's no C (or any language really) type with similar guarantees as `char`, all Diplomat methods that work on "char"s will have to deal with `u32`
  * ICU4X can already do this, future uses might have to define error states
* We will add a `type DiplomatChar = u32`, which parses to `PrimitiveType::Char` and becomes `char32_t` on the ABI and nice types on the FFI (like #364)

**Comment by sffc** [comment]
`char` to me means an `int8_t` so it's extremely good to remove ambiguity if we intend `char` to mean a 32-bit code point value.
