### ISSUE TITLE
cl.exe and clang-cl have no ssize_t

### ISSUE THREAD

**Issue by makotokato** [rust-diplomat/diplomat#326]
When integrating ICU4X with Firefox, Window build cannot compile icu_capi (try build log is https://treeherder.mozilla.org/logviewer?job_id=413380887&repo=try&lineNumber=19287)
```
[task 2023-04-22T08:23:15.509Z] 08:23:15    ERROR -  /builds/worker/checkouts/gecko/third_party/rust/icu_capi/c/include/diplomat_runtime.h(57,24): error: unknown type name 'ssize_t'
[task 2023-04-22T08:23:15.509Z] 08:23:15     INFO -  MAKE_SLICE_VIEW(Isize, ssize_t)
```

When looking diplomat code, runtime.h uses `ssize_t`. But cl.exe (and clang-cl.exe) doesn't have `ssize_t`.  Could you use `ifdef` or something workaround?

If I am something wrong, let me know.

**Comment by Manishearth** [comment]
Do we know what types we _should_ use here?

**Comment by Manishearth** [comment]
It also seems like it's standard and has existed for a while so it might just need some flags

**Comment by Manishearth** [comment]
Ah, it's POSIX standard.

**Comment by makotokato** [comment]
I think that `intptr_t` is better, but both is OK.

**Comment by sffc** [comment]
I've always seen just `size_t`

**Comment by sffc** [comment]
oh I didn't see this was for signed.

**Comment by Manishearth** [comment]
icu_capi patch in https://github.com/unicode-org/icu4x/pull/3401
