### ISSUE TITLE
moving a temporary object prevents copy elision

### ISSUE THREAD

**Issue by makotokato** [rust-diplomat/diplomat#335]
Related to https://github.com/rust-diplomat/diplomat/issues/280.

When using ICU4X's icu_capi as C++ project, I hit a lot of the following warning.

```
 0:13.25 In file included from /mozilla/mozilla-central/intl/lwbrk/WordBreaker.cpp:16:
 0:13.25 /mozilla/mozilla-central/third_party/rust/icu_capi/cpp/include/ICU4XWordSegmenter.hpp:113:66: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
 0:13.25     diplomat_result_out_value = diplomat::Ok<ICU4XWordSegmenter>(std::move(ICU4XWordSegmenter(diplomat_result_raw_out_value.ok)));
 0:13.25                                                                  ^
 0:13.25 /mozilla/mozilla-central/third_party/rust/icu_capi/cpp/include/ICU4XWordSegmenter.hpp:113:66: note: remove std::move call here
 0:13.25     diplomat_result_out_value = diplomat::Ok<ICU4XWordSegmenter>(std::move(ICU4XWordSegmenter(diplomat_result_raw_out_value.ok)));
 0:13.25                                                                  ^~~~~~~~~~     
```

**Comment by Manishearth** [comment]
Ah, this is trickier, it works when there's some constructor being used, but not when the ok value is used directly

This is something we'd need to track in the conversions code to get right; I'm inclined to either:

 - pair this fix with a change that unconditionally generates an ok/err variable via `std::move()` 
 - abandon this

**Comment by Manishearth** [comment]
This _may_ be an issue in cpp2 for primitives (everyone else goes through some temporary)

AIUI primitives are the only situation where `std::move` is actually necessary here, which feels strange.
