### ISSUE TITLE
JS runtime slice code truncates values

### ISSUE THREAD

**Issue by Seally** [rust-diplomat/diplomat#339]
This issue makes it so that functions that call `DiplomatBuf.slice()` do not properly pass values to WASM, so calling functions like `ICU4XLineSegmenter.segment_utf16()` from JS will not produce the correct output.

This line https://github.com/rust-diplomat/diplomat/blob/19b6e413c7510d0942fe7b80aade64d8a77216c2/tool/src/js/runtime.mjs#L87
constructs a `Uint8Array` from a potentially wider typed array like `Uint16Array`. However, this particular signature produces an array with the same number of elements as the source, so values that won't fit into 8 bits will be truncated. So an array like this:

```
Uint16Array(20) [
  3585, 3619, 3640, 3603,
  3634, 3629, 3618, 3656,
  3634, 3648, 3604, 3636,
  3609, 3621, 3633, 3604,
  3626, 3609, 3634, 3617
]
```

would become:

```
Uint8Array(20) [
   1, 35, 56, 19, 50, 45, 34,
  72, 50, 64, 20, 52, 25, 37,
  49, 20, 42, 25, 50, 33
]
```

Easiest fix seems to be changing this to `new Uint8Array(slice.buffer)`. I believe this will also set the two array buffers to be equal (so `oldArray.buffer === newArray.buffer`), so I'm not completely sure if this is OK. 

Note that this change will also affect functions that use the slice's size. For example, in this function

https://github.com/unicode-org/icu4x/blob/e41030cd05732ef7329388bffdd759cac96c2445/ffi/diplomat/js/include/ICU4XLineSegmenter.js#L140

the argument `buf_arg_input.size` might need to be changed to something like `buf_arg_input.size / 2` otherwise the segmented indices will go up to twice the actual length. I'm not sure which files to change for that one (maybe more of an ICU4X issue).

**Comment by Manishearth** [comment]
Oh, nice catch. I think it ought to be fine to move the buffer in, since we do that for Uint8Array anyway.

Might get around to fixing this myself, also happy to accept a PR (ideally one with a previously-failing-now-succeeding test.

> I'm not sure which files to change for that one (maybe more of an ICU4X issue).



No, that's still generated JS code, the JS conversions code needs a fix there.
