### ISSUE TITLE
Enable `Option<T>` for `T` != `Box`

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#354]
Similar to how we transform `Result<T, E>` into `DiplomatResult<T, E>` to pass it through the ABI, we can transform `Option<T>` into `DiplomatResult<T, ()>` inside Diplomat, instead of forcing the user to do this.

ICU4X for example uses `Result<T, ()>` for an API that returns an `Option` in Rust. This then becomes a `DiplomatResult` in C++, and throws an error in JS, which is not in the spirit of the original API. It should become a `std::optional<T>` in C++, `T | null` in TS, and `T?` in Dart.

**Comment by Manishearth** [comment]
https://github.com/rust-diplomat/diplomat/issues/246
