### ISSUE TITLE
Support `&[&str]`

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#378]
This would allow us to get rid of the `ICU4XList` type, which makes the list formatter very allocatey.

**Comment by Manishearth** [comment]
I think this needs to be done in the form of an input iterator or array type.

**Comment by Manishearth** [comment]
I guess actually `&[&str]` is fine for C/C++, but most of the time I feel like an input iterator API is better

**Comment by robertbastian** [comment]
Adding new functionality like this is quite tedious because we have so many backends now. I'll shelve this until we've deleted some.

**Comment by Manishearth** [comment]
Fixed in https://github.com/rust-diplomat/diplomat/pull/458
