### ISSUE TITLE
Fix JS slice borrowing

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#383]
Currently slice borrowing is broken, because we cannot add lifetime edges to the `{prim}Array`s. For a temporary fix we can copy, but we should revisit this in JS 2.

**Comment by robertbastian** [comment]
This also applies to Dart, however there we can return a custom list type instead of the built in typed list. Not sure what we can do in JS

**Comment by Manishearth** [comment]
> we cannot add lifetime edges to the {prim}Arrays

Why not? It's javascript, we can just stash random extra fields in there

If we're worried about reachability we can have a `const LIFETIMES = new Symbol("lifetimes")` in diplomat-runtime and use that as the field name.

**Comment by Manishearth** [comment]
The AST backend is gone now
