### ISSUE TITLE
Add a `DiplomatBytes` type

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#385]
When a Rust API uses `&[u8]` it's unclear whether that means
* raw bytes, as in `ICU4XDataProvider::create_from_byte_slice`, or
* a list of small numerical values, as in `ICU4XBidi::reorder_visual`

In Dart I would like to treat these differently. `DataProvider.fromByteSlice` should accept a `ByteBuffer`, whereas `Bidi.reorderVisual` should accept a `List<int>`.

Making `ICU4XDataProvider::create_from_byte_slice` accept a special `type DiplomatBytes = [u8]` would allow codegen to distinguish these cases.

**Comment by Manishearth** [comment]
Seems fine. Perhaps we should have a general `DiplomatList<T>` which passes down something that is indexable and has a length

**Comment by Manishearth** [comment]
> Well that's just slice

Yeah fair, bytes are typically special here. But in JS for example we can have all kinds of typed byte buffers but it would be nice to accept Normal Arrays.
