### ISSUE TITLE
Only associated functions are supported?

### ISSUE THREAD

**Issue by Chaoses-Ib** [rust-diplomat/diplomat#391]
I tried to generate an FFI definition for a simple function, but diplomat-tool outputs nothing except `diplomat_runtime`. I have read the book and the examples, but all the functions in them are associated functions. I was wondering if diplomat supports ordinary functions? And if so, how do I make it work?
```rust
#[diplomat::bridge]
mod ffi {
    pub fn is_match_u8(pattern: &str, haystack: &str) -> bool {
        todo!()
    }
}
```

I've tried using a zero-sized struct as a workaround, but unfortunately, diplomat doesn't support it either:
```rust
#[diplomat::bridge]
mod ffi {
    // diplomat-tool-0.7.0\src\lib.rs:76:9: A non-opaque zero-sized struct or enum has been defined: ffi::FFI
    pub struct FFI;

    impl FFI {
        pub fn is_match_u8(pattern: &str, haystack: &str) -> bool {
            todo!()
        }
    }
}
```

**Comment by Manishearth** [comment]
Nope, they're not supported. We are open to adding support but it's low priority. I filed an issue for tracking: https://github.com/rust-diplomat/diplomat/issues/392

In the meantime, the workaround is this:

```rust
#[diplomat::bridge]
mod ffi {
    #[diplomat::opaque]
    pub struct FFI;

    impl FFI {
        pub fn is_match_u8(pattern: &str, haystack: &str) -> bool {
            todo!()
        }
    }
}
```

**Comment by Chaoses-Ib** [comment]
Thanks for your tip. I somehow thought adding `opaque` would make diplomat prepend a `this` pointer as the first argument and thus introduce performance overhead.

**Comment by Manishearth** [comment]
Nope, that's only when the function has a `&self` parameter
