### ISSUE TITLE
Should backends be allowed to lazy-destructure structs?

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#405]
This greatly affects lifetime handling strategies.

Currently, the JS backend eagerly destructures structs: when you get a struct over FFI, the JS backend will immediately construct each of its fields and return a pure JS object.

https://github.com/rust-diplomat/diplomat/blob/600ad7d5552cf23b8c891b434fc0c320368d2adb/feature_tests/js/api/OptionStruct.mjs#L6-L20

The Dart backend, however, holds on to the struct received over FFI, and converts fields on-demand as requested.

https://github.com/rust-diplomat/diplomat/blob/600ad7d5552cf23b8c891b434fc0c320368d2adb/feature_tests/dart/lib/src/OptionStruct.g.dart#L16-L27

This is currently extremely broken since calling a field getter twice for an opaque field is UB. This brokenness is fixable: we can have the getter always return a borrow, and also rregister a destructor for the struct itself. I'm not a huge fan of that approach.

Since the brokenness is fixable, it is still a valid approach.

However, I'm trying to make the HIR do most of the work for lifetimes. This requires presuming a strategy here, these two strategies have different needs for lifetimes:

## The eager strategy

In the JS (eager) strategy, the struct constructor needs to also take in an ownership edge array[^1] from the caller for each lifetime parameter on the struct, and pass them in to fields that need them:

https://github.com/rust-diplomat/diplomat/blob/600ad7d5552cf23b8c891b434fc0c320368d2adb/feature_tests/js/api/BorrowedFields.mjs#L4-L7

(This is currently also broken since it's not handling the lifetimes of fields that are references — edges_a should get tacked on to the returned buffers; but that's easily fixed)

Methods do something similar: when constructing a struct or reference they pass in ownership edge arrays for everything that struct/reference borrowed from.

https://github.com/rust-diplomat/diplomat/blob/600ad7d5552cf23b8c891b434fc0c320368d2adb/feature_tests/js/api/Foo.mjs#L55

https://github.com/rust-diplomat/diplomat/blob/600ad7d5552cf23b8c891b434fc0c320368d2adb/feature_tests/js/api/One.mjs#L27

It is able to reach into input structs and get ownership edges for specific fields being borrowed.

The reason JS takes the eager strategy is so that there is no Rust struct type ever held by JS code; it's only temporarily constructed at method boundaries. This is similar to how this stuff works This means it is possible for JS code to pass untyped dicts to methods and have that get automatically constructed.

Now, we could switch JS over to the lazy strategy if we really want, the "untyped dicts" feature can be handled by having methods check `typeof(param)` and call `Struct.from_dict()` or something when it gets a dict. That works fine.

## The lazy strategy

In the Dart (lazy) strategy, the struct will still need to take in ownership edge arrays on construction, one for each lifetime parameter.

There are three ways to handle lifetimes here

**Borowing Strategy A (track edges per-struct-lifetime):** The first way is that the struct constructor still needs to take in such ownership edges, but it needs to store them all, and when returning anything with a lifetime, it needs to tack on the right set of ownership edges. It also needs its own destructor that is _not_ the Rust struct destructor (but is manually written to drop droppable fields). There are a couple other ways of doing this, but the core thing is that it's _different_ from the eager path.

If the struct has _setters_ this gets kinda worse; it needs to be able to _extract_ the ownership edges from the type and _add_ them . It can only clear ownership edge arrays for lifetimes found in _only_ that field, this can be somewhat leaky if a lifetime is used in multiple fields.

**Borowing Strategy B (track edges per-field, eagerly assembled):**  Another strategy is to lazily construct fields, but eagerly store ownership edges per-field. This means that for a type with three fields containing lifetimes, it will contain an array of ownership edges per-lifetimed-field. When that field is read, it will be just-in-time computed from whatever the per-field edges are. When it is set, the per-field edges will be cleared and reset using the set value's lifetimes.

This stores more information per-struct but avoids the setter problem (mostly). However, it makes method stuff much more complicated: if you pass a struct that borrows to a method, the method cannot _in general_ assume much about which field corresponds to which lifetime parameter of the method, since people may heve set fields and the original lifetime bounds of the struct may no longer apply. So the only thing that is possible to do there is to use the entire struct as a ownership edge. This risks retaining more stuff than necessary but can work.

**Borowing Strategy C (flatten all edges into the struct):** _Another_ strategy is to flatten struct lifetimes: the struct just holds on to each ownership edge its fields need, and whenever we pull a struct field we use the entire struct as a lifetime edge. Setters will just add lifetimes to the edge array.

This is by far the simplest strategy. It has the downside of retaining a lot more stuff than necessary, but it basically should work in all scenarios. It seems like no matter what, the lazy strategy involves holding on to more ownership edges than necessary.

I'd probably want us to take this route if we are picking lazy stuff, the other two options feel like they overcomplicate structs or methods.

They all require reading lifetimes from the edges arrays of existing types in setters, though, which is not great: the design was to have these exist solely as GC hints and never be read. This isn't a problem in the eager model since in the eager model the edges arrays are precisely on the types that need them, and we narrowly use those types in the edges arrays of return types whose lifetimes flow from these input fields.

## General thoughts

In general I prefer the eager path: holding on to structs across FFI leads to complexity in the borrowing situation. We used to be lazy in JS and deliberately moved away from that model.

On the other hand, the Dart lazy strategy has the benefit that if your workflow is "construct `Struct::default()`, set fields, pass down", then you don't need to convert `Struct::default()` from Rust and then convert back once you pass it down. This does seem useful.

I'm curious how intentional the Dart lazy strategy is. It would not be hard to switch it over to being eager, I think (quite likely it can be done by _only_ changing the template), but I don't want to change things without understanding how intentional they are.

And if we're picking the lazy strategy for Dart (and for JS?) then we should figure out what borrowing strategy to use. As noted before I prefer C (flattening), even though it's somewhat leaky.

Thoughts?

cc @robertbastian @sffc 

 [^1]: The way lifetimes work in Diplomat for GC'd backends is based on types with lifetimes (opaques/structs/references) taking one or more arrays of "ownership edges", one per lifetime, each array containing references to all possible sources of that borrow, so that the GC can keep those sources alive as long as necessary.

**Comment by Manishearth** [comment]
<details><summary>Scratch code file</summary></details>

```rust
#[opaque]
struct Something;

struct Foo<'a, 'b> {
    x: &'a Something,
    y: &'b SomethingElse<'a>,
}

fn make_foo(x: &'a Something, y: &'b Something<'a>) -> Foo<'a, 'b> {

}


ffi_make_Foo(x: DartSomething, y: DartSomethingElse) -> DartFoo {
    let rust_x = x.underlying_;
    ...
    
    let struc = make_foo(rust_x, rust_y);
    DartFoo::from_raw(struc, [x, y], [y]);
}

impl DartFoo {
    fn from_raw(raw: Foo, edge_a, edge_b) {
        self.underlying = raw;
        self.edges = [edge_a, edge_b];
        ....
        
        // ???
    }
    
    get x() {
        return Something::from_raw(self.underlying_.x, owned = false, [self.edges])
    }
    get y() {
        return SomethingElse::from_raw(self.underlying_.y, owned = false, [self.edges])
    }
}


// Reason to do it lazily:
let x = OptionsBag::default() // convert;
x.foo = ...;
...
use(x) // convert back

```
</details>


The three options we have are:
 - Do eager from-ffi
     - we don't care too much about performance; extra FFI for options bag is nbd
 - The hamfisted approach: do not differentiate edges once you construct a struct. All edges go everywhere. Setters append to edges.
 - We can also separate the treatment of inout and out structs. The hamfister approach is mostly a problem for out structs.
     - inout structs use hamfisted approach or are not allowed to have complex borrowing. This is mostly fine, inout structs are largely constructed to get set once
     - out structs have no setters


General consensus seems to be that it's fine to do eager from-ffi for now. We can revisit in the future.

**Comment by sffc** [comment]
My two cents is that fields should be eager, and if there's something that's slow to fetch, use a function instead of a struct field.

**Comment by Manishearth** [comment]
That's a good point, we do support functions on structs.

**Comment by Manishearth** [comment]
Closing as resolved, the three primary maintainers are in agreement and Robert already migrated Dart to eager
