### ISSUE TITLE
HIR backend for JS

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#420]
We should add it.

**Comment by robertbastian** [comment]
Enum draft:

```js
export class MyEnum {
  constructor(value) {
    if (!["A", "B", "C", "D", "E", "F"].contains(value)) {
      throw SomeError(); // ?
    }
    this.value = value;
  }

  static A = MyEnum("A");
  static B = MyEnum("B");
  static C = MyEnum("C");
  static D = MyEnum("D");
  static E = MyEnum("E");
  static F = MyEnum("F");

  fooMethod() {
    wasm.MyEnum_foo_method(this.toFfi());
  }

  valueOf() {
    return this.value;
  }

  toFfi() {
    switch (this.value) {
      case "A": return -2;
      case "B": return -1;
      case "C": return 0;
      case "D": return 1;
      case "E": return 2;
      case "F": return 3;
      default: return null; // unreachable
    }
  }
}
```

**Comment by Manishearth** [comment]
One thing we want to do here is consistently allow pure-JS and class-based inputs for structs and enums


This means for enums:

```
class MyEnum {
  var discr;
  constructor(value) {
     if typeof(value) == string {
        switch (value) { /* switch on disriminants */}
    } else {
      discr = value.discr;
    }
  }
 toString();
 valueOf();
}
```

All methods accepting enums accept either a list of strings or the enum itself. TypeScript can potentially generate `class Enum` and `class EnumOrStrings` or something if we wish to expose this over TS, but we can also require TS use the typed API.

We do something similar for structs where all methods accepting structs can accept a class or a JS dict/object. Since the struct class will have getters and setters this only really matters in TypeScript.

**Comment by sffc** [comment]
Note: In order to unblock progress, Manish and I are okay if we drop the JS backend from ICU4X 2.0 so long as there is a clear, well-resourced path to get it shortly after.
