### ISSUE TITLE
Specta && Diplomat collaboration?

### ISSUE THREAD

**Issue by JohnScience** [rust-diplomat/diplomat#463]
Hi,

I noticed that `specta` and `diplomat` seek to achieve similar goals. I haven't seen any mention of `specta` in the docs, so I decided to bring up this discussion.

**Comment by Manishearth** [comment]
I saw it a while ago, it's newer and much more focused on type structure, not API, and the design appears to be typescript-first (the website says they plan to add more, but from what I can tell the design is much more possible for managed, interpreted languages)

But yeah might be useful to pick up some tricks from.
