### ISSUE TITLE
Avoid String errors in languages where they won't happen

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#475]
Take this code for example:
```rust
pub fn uppercase(&self, s: &DiplomatStr, locale: &ICU4XLocale, write: &mut DiplomatWriteable) -> Result<(), ICU4XError> {
   self.0
       .uppercase(core::str::from_utf8(s)?, &locale.0.id)
       .write_to(write)?;
   Ok(())
}
```

Now in Dart, for example, the `Utf8Error` won't happen, because Dart only ever passes valid UTF-8. Similarly, we probably want to special-case the `fmt::Error`, because it should manifest in Dart as an `OutOfMemoryError`, not a domain-specific `ICU4XError`. If it was only one or the other, we could teach Diplomat about the special error types, and ignore them in languages where they don't happen. But because it's both of them, do we
* add an enum over both to Diplomat, or
* teach Diplomat to filter these variants from domain-specific error enums, or
* add support for nested `Result`s

**Comment by sffc** [comment]
> teach Diplomat to filter these variants from domain-specific error enums, or

I think probably this; there could be annotations on the enum variants. But I think this can be added later.
