### ISSUE TITLE
Attributes for Param, SelfParam, and StructField types

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#521]
Per https://github.com/rust-lang/rust/issues/60406 and https://doc.rust-lang.org/reference/attributes.html, attributes can be positioned in struct fields or parameters positions. Diplomat currently does not have an `attrs` field for the `Param`, `ParamSelf`, or `StructField` types.

This is something that would be especially nice to have for #500.

So for instance, you'd be able to write something like
```rs
struct SomeStruct {
  #[diplomat::attr(not(dart), disable)]
  pub dart_specific_feature,
}
```

Or

```rs
fn foo(
  #[diplomat::attr(kotlin, rename="someNewNameHere")]
  in : i32
) {}
```

**Comment by Manishearth** [comment]
How would disabling a struct field work? Renaming, sure, but I can't see how disabling would work.

But yes, we should support this. Figuring out the inheritance might be tricky.

**Comment by Manishearth** [comment]
Shouldn't be hard to add support for if you're thinking of doing it!
