### ISSUE TITLE
JS2 Backend: Helper functions in diplomatRuntime to minimize the amount of direct reference to wasm.

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#522]
For instance, functions that return a DiplomatWrite buffer should do this.

**Comment by sffc** [comment]
Both for strings and boxed slices: https://github.com/rust-diplomat/diplomat/pull/487#discussion_r1651473253

**Comment by sffc** [comment]
Note: Partially done with `sliceFromPtr`
