### ISSUE TITLE
JS2 Backend: Are we supporting 'static  lifetimes for items like slices? 

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#529]
The JS2 backend is pretty heavily based on the Dart backend. The Dart backend doesn't support 'static lifetime edges, so we don't either.

Is that something we want to keep? I imagine per #261, we still don't want to support 'static lifetimes, but I would be remiss if I didn't bring this up.

**Comment by Manishearth** [comment]
It's not super important in my book. Optional IMO.
