### ISSUE TITLE
`error: using typedef-name ‘capi::DataProvider’ after ‘struct’`

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#541]
```
/home/runner/work/icu4x/icu4x/ffi/capi/bindings/cpp/Bidi.d.hpp:14:32: error: using typedef-name ‘capi::DataProvider’ after ‘struct’
   14 | namespace capi {typedef struct DataProvider DataProvider; }
```

https://github.com/unicode-org/icu4x/actions/runs/9896813914/job/27339840410?pr=5232

**Comment by Manishearth** [comment]
Ugh I thought I fixed this problem

**Comment by Manishearth** [comment]
Okay, I just learned that struct tags do absolutely nothing in C++ and occupy the same namespace as types, so `typedef struct Foo Foo;` is actually able to conflict with itself sometims. Time to do further hackery in the C-in-cpp codegen.
