### ISSUE TITLE
Demo_Gen: Additional Customization Options

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#606]
- Command line flags for things like:
  - Customizing output of demo-gen/templates
  - Set to be automagical or check for enabled flags.
  - How do we want to add command line options?
    - With [`clap`](https://docs.rs/clap/latest/clap/index.html), we could set each language as a subcommand rather than as an argument.
    - We could also add a `--demoopt` option, or a `--backendopt` option?
    - Will add this to the notes for Thursday's meeting to discuss.
- Ability to override behavior for default renderer with diplomat.config.mjs (things like CSS and the templates file)

**Comment by Manishearth** [comment]
Yeah doing subcommands would be nice.

I think ideally the subcommand settings can also be set via `--config config.toml`

**Comment by ambiguousname** [comment]
I see the `--library-config <PATH>` option, which I think I will use for now.

Currently one issue I can see with the subcommands option is that it changes the order of the command line, from:

```
diplomat-tool.exe [OPTIONS] <TARGET_LANGUAGE> <OUT_FOLDER>
```

to

```
diplomat-tool.exe [OPTIONS] <OUT_FOLDER> <COMMAND>
```
