### ISSUE TITLE
Should we stop splitting out data,len pairs when slices show up in FFI params?

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#613]
Currently, when a slice shows up in the parameter list of a function (but not in a struct), the parameter gets split into a `data, len` pair of parameters. For example, `fn foo(x: &[u8])` would be `extern "C" fn foo(x_data: *const u8, x_len: usize)`. When found in a struct field, this process does not occur, and instead it uses the `DiplomatU8View` type.

I think this leads to a more idiomatic C API based on old C idioms, but really having a unified slice type makes the C nicer overall, and it would simplify codegen. Basically, I'm proposing we _always_ use `DiplomatU8View` and friends.

There's one downside here: FFI/ABI uncertainty around the layouts of `&[u8]` etc. What I propose here is that we:

 - Introduce `diplomat_runtime` `repr(C)` types `DiplomatSlice<T>` and `DiplomatValidatedStr` etc. We already have some of the other types here. They should have helper methods that let one recover the original type.
 - _require_ they be used in struct fields
 - _allow_ usage of idiomatic Rust slice types in function signatures, except we convert with `.into()` (so the actual `extern "C"` layer always uses these `repr(C)` types). We already do this a couple times in the macro. I intend to do something similar with Option support (https://github.com/rust-diplomat/diplomat/issues/246)

Thoughts? @robertbastian @sffc

**Comment by Manishearth** [comment]
In general I don't like complexity in the macro, and the current param-splitting is responsible for a surprising amount of complexity in the macro.

My _hope_ is that the macro really should just be doing:

 - generate the right parameter and return value types of the type
 - call `.into()` on some parameters, perhaps
 - call the underlying function correctly
 - call `into()` on the result, perhaps

**Comment by Manishearth** [comment]
This is ABI breaking, so if we do this, we should do it now.

**Comment by robertbastian** [comment]
I was thinking that just last week when fixing slices in Dart. Having a slice struct on the ABI would simplify a lot of things, and it's still easy to call in C with inline structs.

**Comment by Manishearth** [comment]
I might try and do this tomorrow? Simplifying the macro code is extremely tempting.

**Comment by Manishearth** [comment]
(And my next steps for DiplomatOption involve the macro code _anyway_)

**Comment by sffc** [comment]
I'm fine with this
