### ISSUE TITLE
It should be easy to construct a struct from fields in JS

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#635]
Discovered when attempting to fix https://github.com/rust-diplomat/diplomat/issues/634

Currently JS structs cannot be constructed unless you call a specific method. This is extremely suboptimal.

At the very least there should be a `fromFields()` static function that constructs the struct.

_Ideally_ this should be the constructor. We do already use the constructor for stuff, and I think the best way to handle that is to do something like check if the first parameter is a `Symbol("internal constructor")` that we declare in the runtime. If there is a default ctor, we generate that instead and switch to a `fromFields()`. See https://github.com/rust-diplomat/diplomat/issues/582

Furthermore, methods that take structs should also take objects with the same fields, calling `fromFields()`.

I think the ability to construct a struct without any FFI is a blocker for the backend to be considered finished, the rest are nice to haves.

cc @ambiguousname

**Comment by ambiguousname** [comment]
I thought I created this functionality for the demo gen backend? Nonetheless I think resolving #582 is the best way to handle this, so I can get on this tomorrow

**Comment by ambiguousname** [comment]
Ohhh, I see why this wasn't fixed. I think I may have removed the ptr constructor when testing in ICU4X, but that got lost for whatever reason. Regardless, working on a fix now. Will try to update demo gen accordingly.

**Comment by Manishearth** [comment]
Sounds good. Yeah, I couldn't figure out a convenient way to construct them so I didn't try too hard.
