### ISSUE TITLE
JS fromFFI on structs is incorrect

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#636]
fromFFI looks like this:

https://github.com/rust-diplomat/diplomat/blob/9320edea0fe21bfcdcf19918724fd6bbf88b541d/feature_tests/js/api/BorrowedFields.mjs#L51-L60

However, `ptr` is a `diplomatReceive.buffer`, not a `diplomatReceive`:

https://github.com/rust-diplomat/diplomat/blob/9320edea0fe21bfcdcf19918724fd6bbf88b541d/feature_tests/js/api/BorrowedFields.mjs#L84

In other words, it's a plain integer and has no `getString` (etc) methods. 

One problem with doing arithmetic on `ptr` if we pass `DiplomatReceiveBuf` around is that when it gets passed down to other structs then we lose control of what the `ptr` is. I think what we need to do is pass down the DiplomatReceiveBuf and the offset as a separate parameter, and tweak `getString()` etc to support a separate offset.

https://github.com/rust-diplomat/diplomat/blob/9320edea0fe21bfcdcf19918724fd6bbf88b541d/feature_tests/js/api/NestedBorrowedFields.mjs#L50-L59

I think we need a lot more tests that exercise struct behavior, when passed over FFI in both directions.

**Comment by Manishearth** [comment]
@ambiguousname I think this one is the most urgent one since it's actively blocking the ability to test behavior for bugs like https://github.com/rust-diplomat/diplomat/issues/634

**Comment by ambiguousname** [comment]
Alright, will prioritize in the morning, thanks for letting me know. Agree that we should have more stringent struct tests

**Comment by ambiguousname** [comment]
This should be fixed by #622 (`getStrings` is replaced with the `DiplomatSlice` type), but let me know if there's another way we want to resolve this.
