### ISSUE TITLE
JS Cannot Handle a Result<.., Error> if the Error type is ZST

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#649]
Best seen with TimeZoneMapperId.normalize_iana: `(func $icu4x_TimeZoneIdMapper_normalize_iana_mv1 (type 10) (param i32 i32 i32 i32) (result i32)`

Javascript passes in:

```js
const valueSlice = diplomatRuntime.DiplomatBuf.str8(wasm, value);

const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);

const write = new diplomatRuntime.DiplomatWriteBuf(wasm);
const result = wasm.icu4x_TimeZoneIdMapper_normalize_iana_mv1(diplomatReceive.buffer, this.ffiValue, valueSlice.ptr, valueSlice.size, write.buffer);
```

This is completely new territory for JS, and I'm not sure how WASM expects us to handle this.

**Comment by Manishearth** [comment]
I don't understand what's special about this use case: the diplomatwrite and the result both end up as outparams, yes?

**Comment by ambiguousname** [comment]
In order to read the result, we usually need a `diplomatReceive` buffer, since there are pointers to both the successful result type and the unsuccessful result type that WASM stores for us.

But in this case, there is no room for a buffer for us to read.

Found the LLVM output:

```ll
define dso_local %"diplomat_runtime::result::DiplomatResult<(), errors::ffi::TimeZoneInvalidIdError>" @icu4x_TimeZoneIdMapper_normalize_iana_mv1
(ptr noalias nocapture noundef readonly align 8 dereferenceable(40) %this, 
ptr noundef %value.0, i32 noundef %value.1,
ptr noalias noundef align 4 dereferenceable(28) %write) unnamed_addr #0
```

Which I think means that we axe `diplomatReceive` as a buffer, since there is no reference to a buffer that we place in.

Not sure how to then read the write buffer or error result?

**Comment by ambiguousname** [comment]
Okay, thinking on this I think what the function returns is a pointer to our error result?

**Comment by Manishearth** [comment]
> But in this case, there is no room for a buffer for us to read.


I don't understand what this means in this context.

> I think the write buffer is not used at all when creating an error result. Not sure how to then read the error result? Is it just the pointer that gets output?


LLVM doesn't know anything about the tagging of the union, though?

**Comment by sffc** [comment]
The WASM function is expecting 4 parameters but we are passing it 5, which means one of the parameters is turning into the return value. Is it returning the error value?

I agree that I don't see why DiplomatWrite makes this special. Does `Result<(), Error>` always do this?

**Comment by Manishearth** [comment]
Right, `Result<(), Error>` should have identical handling to structs using an outparam. DiplomatWrite should not make this special.

**Comment by ambiguousname** [comment]
Then it must be JS that treats it as if it's special. Let me take a look

**Comment by ambiguousname** [comment]
Sorry, I assumed `diplomatWrite` was interfering somehow, but really it's just that we don't handle `Result<(), Error>` types correctly.

A simpler test is with `ResultOpaque::new_in_err`.

The JS provides:

```js
const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);
const result = wasm.ResultOpaque_new_in_err(diplomatReceive.buffer, i);
```

The `.ll` file only requires one parameter:

```ll
define dso_local align 4 ptr @_ZN22diplomat_feature_tests6result3ffi12ResultOpaque10new_in_err17hf5b3890d62bbafc8E(i32 %i) unnamed_addr
```

So I think for this, it just returns a pointer to the Error type? And the pointer would probably be null if the error was a success.

Let me know if that sounds correct.

**Comment by ambiguousname** [comment]
Looking at the function (without debug symbols):

```ll
define dso_local align 4 ptr @_ZN22diplomat_feature_tests6result3ffi12ResultOpaque10new_in_err17hf5b3890d62bbafc8E(i32 %i) unnamed_addr #0 {
start:
  %_0 = alloca [4 x i8], align 4
; call alloc::alloc::exchange_malloc
  %_4.i = call ptr @_ZN5alloc5alloc15exchange_malloc17h039a225c8e22cee6E(i32 4, i32 4) #14
  store i32 %i, ptr %_4.i, align 4
  store ptr %_4.i, ptr %_0, align 4
  %0 = load ptr, ptr %_0, align 4
  ret ptr %0
}
```

Seems like it is a pointer that gets allocated and returned, I'll write some tests and submit a PR shortly

**Comment by Manishearth** [comment]
Hmm, that doesn't match the codegen code, which seems to unconditionally produce DiplomatResult.

Either way, this would _only_ work for allocated error types; enum error types would have to be structlike with the `is_ok`

**Comment by Manishearth** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=217b978de8bb84d2344e66f5d3c5a0b5


define { i64, i64 } @thisismyfunction() unnamed_addr #0 !dbg !7 {
start:
  %_0 = alloca [16 x i8], align 8
  br label %bb1, !dbg !41


For `-> DiplomatResult<(), Box<u8>>`

**Comment by Manishearth** [comment]
Though I guess wasm could be doing something different

**Comment by Manishearth** [comment]
Nope, same deal in wasm

`rustc test.rs --target wasm32-unknown-unknown --emit=llvm-ir --crate-type cdylib` (I needed to add `extern crate core` to the test code above to make it work)

```llvm
%"DiplomatResult<(), alloc::boxed::Box<u8>>" = type { %"DiplomatResultValue<(), alloc::boxed::Box<u8>>", i8, [3 x i8] }
%"DiplomatResultValue<(), alloc::boxed::Box<u8>>" = type { [1 x i32] }

; Function Attrs: nounwind
define dso_local %"DiplomatResult<(), alloc::boxed::Box<u8>>" @thisismyfunction() unnamed_addr #0 {
start:
  %_0 = alloca [8 x i8], align 4
  br label %bb1

bb1:                                              ; preds = %bb1, %start
  br label %bb1
}
```

**Comment by Manishearth** [comment]
Okay, but `new_in_err` does seem to produce this when compiled (`cargo rustc -- --emit=llvm-ir`, didn't even need to select the platform). Hm.

`define align 4 ptr @_ZN22diplomat_feature_tests6result3ffi12ResultOpaque10new_in_err17hcc0bfe0620bb03f0E(i32 %i) unnamed_addr #0 personality ptr @rust_eh_personality !dbg !24790 {`

**Comment by Manishearth** [comment]
`--pretty=expanded` gives me this function which seems to be fine

```
        #[no_mangle]
        extern "C" fn ResultOpaque_new_in_err(i: i32)
            -> diplomat_runtime::DiplomatResult<(), Box<ResultOpaque>> {
            ResultOpaque::new_in_err(i).into()
        }
```

**Comment by ambiguousname** [comment]
No, I think I'm totally wrong. I just did a lot of checking and Result<(), Err> is returning things just fine. I just missed the step to convert from LLVM to WASM

**Comment by ambiguousname** [comment]
But there's still a number of parameters mismatch in the WASM for normalize_iana: `(func $icu4x_TimeZoneIdMapper_normalize_iana_mv1 (type 10) (param i32 i32 i32 i32) (result i32)` versus `wasm.icu4x_TimeZoneIdMapper_normalize_iana_mv1(diplomatReceive.buffer, this.ffiValue, valueSlice.ptr, valueSlice.size, write.buffer)`

**Comment by Manishearth** [comment]
@ambiguousname oh. i just realized what went wrong.

You were looking at 

```
define align 4 ptr @_ZN22diplomat_feature_tests6result3ffi12ResultOpaque10new_in_err17hcc0bfe0620bb03f0E(i32 %i) unnamed_addr #0 personality ptr @rust_eh_personality !dbg !24790 {
```

That's the Rust-side function. That's got unstable Rust ABI and a mangled name and is completely irrelevant for WASM. It's called internally by `define { i64, i64 } @ResultOpaque_new_in_err(i32 %i) unnamed_addr #0 !dbg !24882 {`, which is the function you want

**Comment by Manishearth** [comment]
@ambiguousname oh. that's easier to explain. `TimeZoneInvalidIdError` is a zero-sized type.

The JS "return or outparam" heuristic is that single values are returns, multiple values are outparams. result types are outparams _unless_ they are both ZSTs (either `()` or a ZST struct type)

**Comment by Manishearth** [comment]
Diplomat supports ZST structs in a narrow context: they basically can only show up as error types

**Comment by ambiguousname** [comment]
Ahhh, I see. So if there's a ZST error type, there will be no need to allocate a buffer for it? What's the error checking behavior in that case?

**Comment by Manishearth** [comment]
@ambiguousname the wasm function returns a bool, you throw the struct error in the failure case
