### ISSUE TITLE
Diplomat for Java

### ISSUE THREAD

**Issue by sffc** [rust-diplomat/diplomat#68]
This issue is to discuss paths toward Java support in Diplomat.

We had a discussion today to brainstorm some options and ask questions toward this goal.  Here are the notes from that discussion:

- Q: Panama or JNI?
    - Panama is only available in JDK 16+ and only for C. So if you need something right away, JNI seems like the most practical option.
    - Diplomat talks over C ABI. Diplomat generates a C API that is wrapped in all the other languages.
    - Panama is like magic.
- Q: Is there a technical difference between Panama and JNI?
    - There are some advances in Panama's models, but don't know for sure whether there is a real advantage over JNI.
- Q: Any idea when Panama might come to Android?
    - Not aware that it is on their radar.
- Q: GC? Finalizers or something better?
    - Finalizers are not great. But there's no good answer.
- Q: How do we return structs by value? Do we need to malloc? For field access, if we own the struct, can we avoid calling over JNI?
    -  Panama has nice memory segments. That is supported already.
- Q: How should we do error handling?
    - Exceptions are expensive. So if you plan to throw them all the time, you should try to avoid them. But if they are only occasional, maybe exceptions are okay.
    - Or we could use Java Optional. That's like what we are doing in C++.
- Q: Does anyone use JNA?
    - That's probably replaced in favor of Panama. It gives you the ergonomics without the penalty.
- Q: How about WebAssembly? Is there a future there for WASM/Java interop?
    - That sounds cool, but not aware of current efforts to make that work. WASM on the Server sounds cool and would like to learn more about it.
    - The WebAssembly folks have been pushing for WASM being more of an industry standard bytecode format.
- Q: How about GraalVM? It supports both WASM and Java.
    - Not aware of work to adopt GraalVM.

**Comment by Manishearth** [comment]
Closed in favor of #144
