### ISSUE TITLE
Use multi-level argument names in demo_gen

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#713]
Instead of flattening recursive parameters, like `year`, `month`, `day` if the argument is a `Date`, qualify them: `date:month`. Argument names are usually written in the context of a type, so when that is missing they are hard to interpret (e.g. `name` for the locale argument).

Single-argument names can be omitted, i.e. `locale:name` can just be `locale`.

<img width="659" alt="Screenshot 2024-10-23 at 15 59 13" src="https://github.com/user-attachments/assets/b40e1da0-13df-42f5-957e-a94226af5ca9">

**Comment by ambiguousname** [comment]
Overlaps with #611. I like this solution, but I also know @sffc had some opinions. Does this sound good?

**Comment by Manishearth** [comment]
I like this, though there's another option which is to store this as some form of metadata that the renderer can use, potentially to group things into regions, or use colons, or something else.

**Comment by robertbastian** [comment]
This is a low hanging fruit that doesn't require annotating all of ICU4X. Metadata can be built on top of it, but that's considerably more work. The current state is really not good.

**Comment by Manishearth** [comment]
Oh 100% we should do the easy thing first

**Comment by sffc** [comment]
I'm good with this, although I still think the better solution is to just name parameters less ambiguously.

**Comment by ambiguousname** [comment]
Ok, I'm on this when I have some free time

**Comment by Manishearth** [comment]
> I like this, though there's another option which is to store this as some form of metadata that the renderer can use, potentially to group things into regions, or use colons, or something else.

Mockup of a good UI for this with fieldset

![image](https://github.com/user-attachments/assets/fec18dee-8e1c-4fbe-ad56-3b6db17b54a9)
