### ISSUE TITLE
Ignore `use` tokens that are inside of `cfg(test)`

### ISSUE THREAD

**Issue by gregtatum** [rust-diplomat/diplomat#73]
My tests are triggering the `UseTree::Glob(_) => todo!("Glob imports are not yet supported {:?}", base_path),` since I'm doing:

```rust
#[cfg(test)]
mod test {
    use super::*;
    ...
}
```

I put a print statement in `Module::from_syn` and the Item doesn't seem to have the context of where it is in the AST to filter them out. I'm not sure how generalized this kind of behavior could be, but at least at this point it would be nice to not analyze tests.

```
extract_imports ItemUse {
    attrs: [],
    vis: Inherited,
    use_token: Use,
    leading_colon: None,
    tree: Path(
        UsePath {
            ident: Ident {
                sym: super,
                span: bytes(14966..14971),
            },
            colon2_token: Colon2,
            tree: Glob(
                UseGlob {
                    star_token: Star,
                },
            ),
        },
    ),
    semi_token: Semi,
}
```

**Comment by shadaj** [comment]
This definitely looks like a bug, we shouldn't be doing anything with non-diplomat modules other than identifying submodules.

**Comment by Manishearth** [comment]
Yes. (Also I'd like to stop us looking at imports at all unless tagged)

**Comment by Manishearth** [comment]
Yeah we shouldn't be parsing globs outside of bridge modules at all.
