### ISSUE TITLE
WASM ABI: Functions that return structs of only one field (even nested) are collapsed

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#739]
As seen in #734. If I have:

```rs
#[derive(Default)]
pub struct CyclicStructA {
  pub a: CyclicStructB,
}
#[derive(Default)]
pub struct CyclicStructB {
  pub field: u8,
}

impl CyclicStructA {
  fn default() -> CyclicStructA {
    CyclicStructA { a: CyclicStructB { field: 0 } }
  }
}
```

Then the function signature turns out to be:
`func $CyclicStructA_default (type 14) (result i32)`

The way we figure it in Diplomat, we expect a function signature:
`func $CyclicStructA_default (param i32)`

So that we can pass in a pointer to then grab our struct information.

If I add a second field to `CyclicStructA` (something like `b: u8`), then the function signature for `default` matches what we would expect:

`func $CyclicStructA_default (type 1) (param i32)`

So regardless of how much the structs are nested[^1], if they only consist of one parameter, then pointers are dropped entirely. For functions that return a struct (or a struct inside a struct, etc.) with one field, they just return the field's value.

Very much in contradiction with how the ABI almost always returns structs, so this is fairly annoying.

[^1]: If I added `CyclicStructAUpper` that only took `CyclicStructA` as a field, then any functions that returned `CyclicStructAUpper` would have the same behavior.

**Comment by Manishearth** [comment]
wait, did we not handle this already? The old backend did, it seemed like the new one did too with its scalar heuristics

**Comment by ambiguousname** [comment]
Well I can say for certain that we don't for the new backend, as I've gotten errors as described above. I can't speak for the old backend, however.
