### ISSUE TITLE
Add support for `opaque` enums

### ISSUE THREAD

**Issue by emarteca** [rust-diplomat/diplomat#740]
We should add support for exposing non-C-like enums across the language boundary through support of the `opaque` attribute on enums.

Here, I think the other language wouldn't be able to reason about the enum's variants, and would interact with it just like an opaque struct.

**Comment by Manishearth** [comment]
I suspect this is pretty easily done by just changing parsing to allow it.

**Comment by emarteca** [comment]
That makes sense, that's what I was hoping too. I'll test it out
