### ISSUE TITLE
Support customization of C++ types used during code generation

### ISSUE THREAD

**Issue by dminor** [rust-diplomat/diplomat#93]
Diplomat currently supports code generation for the C++ standard library, but projects may want to generate code that relies upon other libraries, e.g. abseil or Mozilla's mfbt.

One idea would be able to provide an optional configuration file that would define which headers to include and the name to use for each required type, e.g. std::unique_ptr or mozilla::UniquePtr.

**Comment by Manishearth** [comment]
I think @gregtatum has been looking into this!

**Comment by gregtatum** [comment]
@dminor and I have been discussing this a bit together when looking into Gecko integrations. I think he might be looking into it a bit as a way to get into some Diplomat work. I don't know if you have any existing ideas @Manishearth on the design of it, but it would be nice to start some experimentation with it, especially as the use of C++20 features block any Gecko integration, which is sticking with C++17 until C++20 implementations stabilize.

**Comment by Manishearth** [comment]
Yeah, go for it! I don't have the bandwidth to do any coding on this myself but I think we've chatted a bit on potential solutions and I was positive of the direction y'all were thinking of taking (having some way of specifying format string templates in a toml file)
